import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          AdminManageStudentsProfile(),
        ]),
      ),
    );
  }
}

class AdminManageStudentsProfile extends StatelessWidget {
  const AdminManageStudentsProfile({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 1015,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFFFCFCFC)),
          child: Stack(
            children: [
              Positioned(
                left: 20,
                top: 120,
                child: SizedBox(
                  width: 350,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 32,
                    children: [
                      SizedBox(
                        width: double.infinity,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 32,
                          children: [
                            SizedBox(
                              width: double.infinity,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 10,
                                children: [
                                  Container(
                                    transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                                    height: 24,
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      spacing: 10,
                                      children: [
                                      ,
                                      ],
                                    ),
                                  ),
                                  Text(
                                    'edit student Info',
                                    style: TextStyle(
                                      color: const Color(0xFF363636),
                                      fontSize: 20,
                                      fontFamily: 'Aeonik TRIAL',
                                      fontWeight: FontWeight.w700,
                                      letterSpacing: -0.60,
                                    ),
                                  ),
                                  Container(
                                    width: 24,
                                    height: 24,
                                    clipBehavior: Clip.antiAlias,
                                    decoration: BoxDecoration(),
                                    child: Stack(),
                                  ),
                                ],
                              ),
                            ),
                            SizedBox(
                              width: 326,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 32,
                                children: [
                                  SizedBox(
                                    width: double.infinity,
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      spacing: 24,
                                      children: [
                                        Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 16,
                                          children: [
                                            Container(
                                              width: 160,
                                              height: 160,
                                              decoration: ShapeDecoration(
                                                image: DecorationImage(
                                                  image: NetworkImage("https://placehold.co/160x160"),
                                                  fit: BoxFit.fill,
                                                ),
                                                shape: OvalBorder(),
                                              ),
                                            ),
                                            Text(
                                              'Anzir Rahman Khan',
                                              style: TextStyle(
                                                color: const Color(0xFF363636),
                                                fontSize: 24,
                                                fontFamily: 'Aeonik TRIAL',
                                                fontWeight: FontWeight.w700,
                                                letterSpacing: -0.72,
                                              ),
                                            ),
                                          ],
                                        ),
                                        SizedBox(
                                          width: double.infinity,
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 8,
                                            children: [
                                              SizedBox(
                                                width: double.infinity,
                                                child: Row(
                                                  mainAxisSize: MainAxisSize.min,
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  crossAxisAlignment: CrossAxisAlignment.center,
                                                  spacing: 32,
                                                  children: [
                                                    SizedBox(
                                                      width: 64.32,
                                                      child: Column(
                                                        mainAxisSize: MainAxisSize.min,
                                                        mainAxisAlignment: MainAxisAlignment.start,
                                                        crossAxisAlignment: CrossAxisAlignment.center,
                                                        spacing: 6.15,
                                                        children: [
                                                          SizedBox(
                                                            width: 64.32,
                                                            height: 64.32,
                                                            child: Stack(
                                                              children: [
                                                                Positioned(
                                                                  left: 0,
                                                                  top: 0,
                                                                  child: SizedBox(
                                                                    width: 64.32,
                                                                    height: 64.32,
                                                                    child: Stack(
                                                                      children: [
                                                                        Positioned(
                                                                          left: 7.15,
                                                                          top: 7.15,
                                                                          child: Container(
                                                                            width: 50.02,
                                                                            height: 50.02,
                                                                            decoration: ShapeDecoration(
                                                                              color: Colors.white,
                                                                              shape: OvalBorder(),
                                                                            ),
                                                                          ),
                                                                        ),
                                                                        Positioned(
                                                                          left: 7.15,
                                                                          top: 7.15,
                                                                          child: Container(
                                                                            width: 50.02,
                                                                            height: 50.02,
                                                                            decoration: ShapeDecoration(
                                                                              gradient: LinearGradient(
                                                                                begin: Alignment(0.02, 0.00),
                                                                                end: Alignment(0.02, 0.97),
                                                                                colors: [const Color(0xFFAD66FF), const Color(0xFF7E07E0)],
                                                                              ),
                                                                              shape: OvalBorder(),
                                                                            ),
                                                                          ),
                                                                        ),
                                                                      ],
                                                                    ),
                                                                  ),
                                                                ),
                                                                Positioned(
                                                                  left: 28.59,
                                                                  top: 33.95,
                                                                  child: Container(
                                                                    width: 7.15,
                                                                    height: 28.59,
                                                                    decoration: BoxDecoration(color: const Color(0xFFF55462)),
                                                                  ),
                                                                ),
                                                              ],
                                                            ),
                                                          ),
                                                          Container(
                                                            width: 30.37,
                                                            height: 9.53,
                                                            padding: const EdgeInsets.symmetric(horizontal: 3.57, vertical: 2.38),
                                                            decoration: ShapeDecoration(
                                                              shape: RoundedRectangleBorder(
                                                                borderRadius: BorderRadius.circular(24.71),
                                                              ),
                                                            ),
                                                            child: Row(
                                                              mainAxisSize: MainAxisSize.min,
                                                              mainAxisAlignment: MainAxisAlignment.center,
                                                              crossAxisAlignment: CrossAxisAlignment.center,
                                                              spacing: 2.98,
                                                              children: [
                                                                Text(
                                                                  'Top 10%',
                                                                  style: TextStyle(
                                                                    color: const Color(0xFF363636),
                                                                    fontSize: 12.31,
                                                                    fontFamily: 'Aeonik TRIAL',
                                                                    fontWeight: FontWeight.w700,
                                                                  ),
                                                                ),
                                                              ],
                                                            ),
                                                          ),
                                                        ],
                                                      ),
                                                    ),
                                                    SizedBox(
                                                      width: 64.32,
                                                      child: Column(
                                                        mainAxisSize: MainAxisSize.min,
                                                        mainAxisAlignment: MainAxisAlignment.start,
                                                        crossAxisAlignment: CrossAxisAlignment.center,
                                                        spacing: 6.15,
                                                        children: [
                                                          SizedBox(
                                                            width: 64.32,
                                                            height: 64.32,
                                                            child: Stack(
                                                              children: [
                                                                Positioned(
                                                                  left: 0,
                                                                  top: 0,
                                                                  child: SizedBox(
                                                                    width: 64.32,
                                                                    height: 64.32,
                                                                    child: Stack(
                                                                      children: [
                                                                        Positioned(
                                                                          left: 7.15,
                                                                          top: 7.15,
                                                                          child: Container(
                                                                            width: 50.02,
                                                                            height: 50.02,
                                                                            decoration: ShapeDecoration(
                                                                              color: Colors.white,
                                                                              shape: OvalBorder(),
                                                                            ),
                                                                          ),
                                                                        ),
                                                                        Positioned(
                                                                          left: 7.15,
                                                                          top: 7.15,
                                                                          child: Container(
                                                                            width: 50.02,
                                                                            height: 50.02,
                                                                            decoration: ShapeDecoration(
                                                                              gradient: LinearGradient(
                                                                                begin: Alignment(0.00, 0.00),
                                                                                end: Alignment(0.00, 1.00),
                                                                                colors: [const Color(0xFFFF7E7D), const Color(0xFFEB2E4A)],
                                                                              ),
                                                                              shape: OvalBorder(),
                                                                            ),
                                                                          ),
                                                                        ),
                                                                      ],
                                                                    ),
                                                                  ),
                                                                ),
                                                                Positioned(
                                                                  left: 28.59,
                                                                  top: 33.95,
                                                                  child: Container(
                                                                    width: 7.15,
                                                                    height: 28.59,
                                                                    decoration: BoxDecoration(color: const Color(0xFFF55462)),
                                                                  ),
                                                                ),
                                                              ],
                                                            ),
                                                          ),
                                                          Container(
                                                            width: 30.37,
                                                            height: 9.53,
                                                            padding: const EdgeInsets.symmetric(horizontal: 3.57, vertical: 2.38),
                                                            decoration: ShapeDecoration(
                                                              shape: RoundedRectangleBorder(
                                                                borderRadius: BorderRadius.circular(24.71),
                                                              ),
                                                            ),
                                                            child: Row(
                                                              mainAxisSize: MainAxisSize.min,
                                                              mainAxisAlignment: MainAxisAlignment.center,
                                                              crossAxisAlignment: CrossAxisAlignment.center,
                                                              spacing: 2.98,
                                                              children: [
                                                                Text(
                                                                  'Top 5%',
                                                                  style: TextStyle(
                                                                    color: const Color(0xFF363636),
                                                                    fontSize: 12.31,
                                                                    fontFamily: 'Aeonik TRIAL',
                                                                    fontWeight: FontWeight.w700,
                                                                  ),
                                                                ),
                                                              ],
                                                            ),
                                                          ),
                                                        ],
                                                      ),
                                                    ),
                                                    SizedBox(
                                                      width: 64.32,
                                                      child: Column(
                                                        mainAxisSize: MainAxisSize.min,
                                                        mainAxisAlignment: MainAxisAlignment.start,
                                                        crossAxisAlignment: CrossAxisAlignment.center,
                                                        spacing: 6.15,
                                                        children: [
                                                          SizedBox(
                                                            width: 64.32,
                                                            height: 64.32,
                                                            child: Stack(
                                                              children: [
                                                                Positioned(
                                                                  left: 0,
                                                                  top: 0,
                                                                  child: SizedBox(
                                                                    width: 64.32,
                                                                    height: 64.32,
                                                                    child: Stack(
                                                                      children: [
                                                                        Positioned(
                                                                          left: 7.15,
                                                                          top: 7.15,
                                                                          child: Container(
                                                                            width: 50.02,
                                                                            height: 50.02,
                                                                            decoration: ShapeDecoration(
                                                                              color: Colors.white,
                                                                              shape: OvalBorder(),
                                                                            ),
                                                                          ),
                                                                        ),
                                                                        Positioned(
                                                                          left: 7.15,
                                                                          top: 7.15,
                                                                          child: Container(
                                                                            width: 50.02,
                                                                            height: 50.02,
                                                                            decoration: ShapeDecoration(
                                                                              gradient: LinearGradient(
                                                                                begin: Alignment(0.00, 0.00),
                                                                                end: Alignment(0.00, 1.00),
                                                                                colors: [const Color(0xFF575753), const Color(0xFF403F36)],
                                                                              ),
                                                                              shape: OvalBorder(),
                                                                            ),
                                                                          ),
                                                                        ),
                                                                      ],
                                                                    ),
                                                                  ),
                                                                ),
                                                                Positioned(
                                                                  left: 28.59,
                                                                  top: 33.95,
                                                                  child: Container(
                                                                    width: 7.15,
                                                                    height: 28.59,
                                                                    decoration: BoxDecoration(color: const Color(0xFFF55462)),
                                                                  ),
                                                                ),
                                                              ],
                                                            ),
                                                          ),
                                                          Container(
                                                            width: 30.37,
                                                            height: 9.53,
                                                            padding: const EdgeInsets.symmetric(horizontal: 3.57, vertical: 2.38),
                                                            decoration: ShapeDecoration(
                                                              shape: RoundedRectangleBorder(
                                                                borderRadius: BorderRadius.circular(24.71),
                                                              ),
                                                            ),
                                                            child: Row(
                                                              mainAxisSize: MainAxisSize.min,
                                                              mainAxisAlignment: MainAxisAlignment.center,
                                                              crossAxisAlignment: CrossAxisAlignment.center,
                                                              spacing: 2.98,
                                                              children: [
                                                                Text(
                                                                  'Top 1%',
                                                                  style: TextStyle(
                                                                    color: const Color(0xFF363636),
                                                                    fontSize: 12.31,
                                                                    fontFamily: 'Aeonik TRIAL',
                                                                    fontWeight: FontWeight.w700,
                                                                  ),
                                                                ),
                                                              ],
                                                            ),
                                                          ),
                                                        ],
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  SizedBox(
                                    width: double.infinity,
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      spacing: 16,
                                      children: [
                                        Container(
                                          width: double.infinity,
                                          padding: const EdgeInsets.symmetric(horizontal: 40),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 10,
                                            children: [
                                              Text(
                                                'Department',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w400,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                              Text(
                                                'CSE',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        Container(
                                          width: double.infinity,
                                          padding: const EdgeInsets.symmetric(horizontal: 40),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 10,
                                            children: [
                                              Text(
                                                'Faculty',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w400,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                              Text(
                                                'FSIT',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        Container(
                                          width: double.infinity,
                                          padding: const EdgeInsets.symmetric(horizontal: 40),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 10,
                                            children: [
                                              Text(
                                                'Batch',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w400,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                              Text(
                                                '61',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        Container(
                                          width: double.infinity,
                                          padding: const EdgeInsets.symmetric(horizontal: 40),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 10,
                                            children: [
                                              Text(
                                                'Section',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w400,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                              Text(
                                                'P',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        Container(
                                          width: double.infinity,
                                          padding: const EdgeInsets.symmetric(horizontal: 40),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 10,
                                            children: [
                                              Text(
                                                'CGPA',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w400,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                              Text(
                                                '3.99',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        Container(
                                          width: double.infinity,
                                          padding: const EdgeInsets.symmetric(horizontal: 40),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 10,
                                            children: [
                                              Text(
                                                'Acheivements',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w400,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                              Text(
                                                '5',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        Container(
                                          width: double.infinity,
                                          padding: const EdgeInsets.symmetric(horizontal: 40),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 10,
                                            children: [
                                              Text(
                                                'Co-curricular',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w400,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                              Text(
                                                'Yes',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        Container(
                                          width: double.infinity,
                                          padding: const EdgeInsets.symmetric(horizontal: 40),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 10,
                                            children: [
                                              Text(
                                                'Extra-Curricular',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w400,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                              Text(
                                                'Yes',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        Container(
                                          width: double.infinity,
                                          padding: const EdgeInsets.symmetric(horizontal: 40),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 10,
                                            children: [
                                              Text(
                                                'Rank',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w400,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                              Text(
                                                '1',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        Container(
                                          width: double.infinity,
                                          padding: const EdgeInsets.symmetric(horizontal: 40),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 10,
                                            children: [
                                              Text(
                                                'Position',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w400,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                              Text(
                                                '1',
                                                style: TextStyle(
                                                  color: const Color(0xFF8E8E8E),
                                                  fontSize: 14,
                                                  fontFamily: 'Aeonik TRIAL',
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: -0.42,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      SizedBox(
                        width: double.infinity,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 16,
                          children: [
                            Container(
                              width: double.infinity,
                              height: 54,
                              padding: const EdgeInsets.symmetric(horizontal: 100, vertical: 16),
                              decoration: ShapeDecoration(
                                color: const Color(0xFF363636),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(83),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 10,
                                children: [
                                  Text(
                                    'Edit',
                                    style: TextStyle(
                                      color: const Color(0xFFF6F6F6),
                                      fontSize: 20,
                                      fontFamily: 'Aeonik TRIAL',
                                      fontWeight: FontWeight.w700,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: double.infinity,
                              height: 54,
                              padding: const EdgeInsets.symmetric(horizontal: 100, vertical: 16),
                              decoration: ShapeDecoration(
                                shape: RoundedRectangleBorder(
                                  side: BorderSide(
                                    width: 2,
                                    color: const Color(0xFF363636),
                                  ),
                                  borderRadius: BorderRadius.circular(83),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 10,
                                children: [
                                  Text(
                                    'Cancel',
                                    style: TextStyle(
                                      color: const Color(0xFF363636),
                                      fontSize: 20,
                                      fontFamily: 'Aeonik TRIAL',
                                      fontWeight: FontWeight.w700,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 48,
                child: SizedBox(
                  width: 350,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 214,
                    children: [
                      Container(
                        width: 109.71,
                        height: 32,
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: NetworkImage("https://placehold.co/110x32"),
                            fit: BoxFit.cover,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}