import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [Menu()])),
    );
  }
}

class Menu extends StatelessWidget {
  const Menu({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 294,
          height: 844,
          padding: const EdgeInsets.only(
            top: 48,
            left: 24,
            right: 24,
            bottom: 76,
          ),
          decoration: BoxDecoration(
            color: Colors.white,
            boxShadow: [
              BoxShadow(
                color: Color(0x19000000),
                blurRadius: 29,
                offset: Offset(13, 0),
                spreadRadius: 0,
              ),
              BoxShadow(
                color: Color(0x16000000),
                blurRadius: 53,
                offset: Offset(53, 0),
                spreadRadius: 0,
              ),
              BoxShadow(
                color: Color(0x0C000000),
                blurRadius: 71,
                offset: Offset(119, 0),
                spreadRadius: 0,
              ),
              BoxShadow(
                color: Color(0x02000000),
                blurRadius: 84,
                offset: Offset(211, 0),
                spreadRadius: 0,
              ),
              BoxShadow(
                color: Color(0x00000000),
                blurRadius: 92,
                offset: Offset(330, 0),
                spreadRadius: 0,
              ),
            ],
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              SizedBox(
                width: double.infinity,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Container(
                      width: 109.71,
                      height: 32,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: NetworkImage("https://placehold.co/110x32"),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                    SizedBox(
                      width: double.infinity,
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          SizedBox(
                            width: 246,
                            child: Text(
                              'Dashboard',
                              style: TextStyle(
                                color: const Color(0xFF7F7F7F),
                                fontSize: 20,
                                fontFamily: 'Aeonik TRIAL',
                                fontWeight: FontWeight.w700,
                                letterSpacing: -0.60,
                              ),
                            ),
                          ),
                          Container(
                            width: double.infinity,
                            height: 1,
                            decoration: BoxDecoration(
                              color: const Color(0xFFD9D9D9),
                            ),
                          ),
                          SizedBox(
                            width: 246,
                            child: Text(
                              'Manage Faculty',
                              style: TextStyle(
                                color: const Color(0xFF7F7F7F),
                                fontSize: 20,
                                fontFamily: 'Aeonik TRIAL',
                                fontWeight: FontWeight.w700,
                                letterSpacing: -0.60,
                              ),
                            ),
                          ),
                          Container(
                            width: double.infinity,
                            height: 1,
                            decoration: BoxDecoration(
                              color: const Color(0xFFD9D9D9),
                            ),
                          ),
                          SizedBox(
                            width: 246,
                            child: Text(
                              'Manage Students',
                              style: TextStyle(
                                color: const Color(0xFF7F7F7F),
                                fontSize: 20,
                                fontFamily: 'Aeonik TRIAL',
                                fontWeight: FontWeight.w700,
                                letterSpacing: -0.60,
                              ),
                            ),
                          ),
                          Container(
                            width: double.infinity,
                            height: 1,
                            decoration: BoxDecoration(
                              color: const Color(0xFFD9D9D9),
                            ),
                          ),
                          Text(
                            'Settings',
                            style: TextStyle(
                              color: const Color(0xFF7F7F7F),
                              fontSize: 20,
                              fontFamily: 'Aeonik TRIAL',
                              fontWeight: FontWeight.w700,
                              letterSpacing: -0.60,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              SizedBox(
                width: 246,
                child: Text(
                  'Logout',
                  style: TextStyle(
                    color: const Color(0xFF7F7F7F),
                    fontSize: 20,
                    fontFamily: 'Aeonik TRIAL',
                    fontWeight: FontWeight.w700,
                    letterSpacing: -0.60,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
