import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [AdminStudentListSearch()])),
    );
  }
}

class AdminStudentListSearch extends StatelessWidget {
  const AdminStudentListSearch({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFFFCFCFC)),
          child: Stack(
            children: [
              Positioned(
                left: 20,
                top: 48,
                child: SizedBox(
                  width: 350,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      SizedBox(
                        width: double.infinity,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Text(
                              'Student List',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: const Color(0xFF1B1B1B),
                                fontSize: 20,
                                fontFamily: 'Aeonik TRIAL',
                                fontWeight: FontWeight.w700,
                                letterSpacing: -0.60,
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: double.infinity,
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            side: BorderSide(
                              width: 1,
                              color: const Color(0xFFBFBFBF),
                            ),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Text(
                              'Search ID, Section, Batch',
                              style: TextStyle(
                                color: const Color(0xFFBFBFBF),
                                fontSize: 16,
                                fontFamily: 'Aeonik TRIAL',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: double.infinity,
                        padding: const EdgeInsets.symmetric(vertical: 12),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              '221-15-5832',
                              style: TextStyle(
                                color: const Color(0xFF7F7F7F),
                                fontSize: 16,
                                fontFamily: 'Aeonik TRIAL',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            SizedBox(height: 12), // Added spacing
                            Text(
                              '221-15-5832',
                              style: TextStyle(
                                color: const Color(0xFF7F7F7F),
                                fontSize: 16,
                                fontFamily: 'Aeonik TRIAL',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            SizedBox(height: 12), // Added spacing
                            Text(
                              '221-15-5832',
                              style: TextStyle(
                                color: const Color(0xFF7F7F7F),
                                fontSize: 16,
                                fontFamily: 'Aeonik TRIAL',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            SizedBox(height: 12), // Added spacing
                            Text(
                              '221-15-5832',
                              style: TextStyle(
                                color: const Color(0xFF7F7F7F),
                                fontSize: 16,
                                fontFamily: 'Aeonik TRIAL',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            SizedBox(height: 12), // Added spacing
                            Text(
                              '221-15-5832',
                              style: TextStyle(
                                color: const Color(0xFF7F7F7F),
                                fontSize: 16,
                                fontFamily: 'Aeonik TRIAL',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            SizedBox(height: 12), // Added spacing
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
